# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6226e13008d96630853c8d1505664518157e84a589c620f89adaba99aeade19df01f3706e2e6279f399a8d1c3dabd1a03a972408a2a933d5a31b1f9f103d1e8a

test:
  secret_key_base: 49cdd1ca8da155a7a26a0752551b24e1bf8dc839a63dae167e763b856a8bd6edfe3c40b34c1db0ccfeb100715d6c5cc627384df3acd177f649d6324478930bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6226e13008d96630853c8d1505664518157e84a589c620f89adaba99aeade19df01f3706e2e6279f399a8d1c3dabd1a03a972408a2a933d5a31b1f9f103d1e8a
